spring:
  application:
    name: auth-service
  config:
    import: optional:file:auth-service/.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    queue-config:
      queue-name: ${RABBITMQ_QUEUE_NAME}
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key: ${RABBITMQ_ROUTING_KEY}


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-Pool
  jpa:
    database-platform: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    enabled: true

server:
  port: 8087
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    deep-linking: true
    default-models-expand-depth: -1
    show-extensions: true
    validator-url: null

jwt:
  access-token-secret: ${ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${REFRESH_TOKEN_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG