spring:
  application:
    name: notification-service
  config:
    import: optional:file:notification-service/.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP-Pool
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    queue-config:
      queue-name: ${RABBITMQ_QUEUE_NAME}
      exchange: ${RABBITMQ_EXCHANGE_NAME}
      routing-key: ${RABBITMQ_ROUTING_KEY}
  jpa:
    database-platform: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      compression-type: snappy
      batch-size: 16384

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}

server:
  port: 8086
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    deep-linking: true
    default-models-expand-depth: -1
    show-extensions: true
    validator-url: null

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  bearer-only: true
  admin:
    realm: ${KEYCLOAK_ADMIN_REALM}
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}


firebase:
  service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}