server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: 46.29.239.208:29094

atm:
  enabled: true
  kafka:
    deposit-topic:
      name: "DEPOSIT"
    withdrawal-topic:
      name: "WITHDRAWAL"

eureka:
  client:
    service-url:
      defaultZone: http://46.29.239.208:8761/eureka/