spring:
  application:
    name: api-gateway
  config:
    import: optional:file:gateway/.env[.properties]
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuerUri}
          jwk-set-uri: ${keycloak.jwkSetUri}


keycloak:
  issuerUri: http://46.29.239.208:8089/realms/app-realm
  jwkSetUri: http://46.29.239.208:8089/realms/app-realm/protocol/openid-connect/certs

eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true