spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/credit/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: core-query
          uri: lb://core-query
          predicates:
            - Path=/api/account/**

        - id: client-interface
          uri: lb://client-interface
          predicates:
            - Path=/client/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true