spring:
  application:
    name: credit-service
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    url: jdbc:postgresql://46.29.239.208:5429/credit
    username: ${POSTGRES_USER:credit_user}
    password: ${POSTGRES_PASSWORD:credit_password_strongvery}
  flyway:
    enabled: true
    locations:
      - migration
  rabbitmq:
    host: 46.29.239.208
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 5
    exchange: "credit-exchange"
    queues:
      creditCreateRequest: "credit.create.request"
      creditCreateResponse: "credit.create.response"
      paymentRequest: "credit.payment.request"
      paymentResponse: "credit.payment.response"
    routing-keys:
      creditCreateRequest: "credit.create.request"
      creditCreateResponse: "credit.create.response"
      paymentRequest: "credit.payment.request"
      paymentResponse: "credit.payment.response"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://46.29.239.208:8089/realms/app-realm}
          jwk-set-uri: ${JWK_SET_URI:http://46.29.239.208:8089/realms/app-realm/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: 46.29.239.208:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      compression-type: snappy
      batch-size: 16384
  data:
    redis:
      host: 46.29.239.208
      port: 6379
      username: veryHardAdmin
      password: verystrongwordpassredis
      client-type: lettuce
      timeout: 10s
keycloak:
  resource: ${KEYCLOAK_RESOURCE:spring-app}
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
random-error:
  enabled: true