server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/core-service
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    url: jdbc:postgresql://postgres:5432/core-service
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  jpa:
    hibernate:
      ddl-auto: validate