server:
  port: 8090

spring:
  application:
    name: core
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/core-service
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    url: jdbc:postgresql://postgres:5432/core-service
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://46.29.239.208:8089/realms/app-realm
          jwk-set-uri: http://46.29.239.208:8089/realms/app-realm/protocol/openid-connect/certs

resilience4j:
  circuitbreaker:
    configs:
      currencyService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

core:
  kafka:
    transaction-topic:
      name: "TRANSACTION_PROCESSING"
  currency:
    api:
      valute:
        url: "https://cbr.ru/scripts/XML_valFull.asp"
      currency:
        url: "https://www.cbr.ru/scripts/XML_daily.asp"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/