spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/core-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/core-service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${core.blocking.kafka-properties.bootstrap-servers}

core:
  enabled: true
  blocking:
    enabled: true
    kafka-properties:
      blocking-topic:
        name: "user_blocked"
      bootstrap-servers: localhost:29092