spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    url: jdbc:postgresql://localhost:5432/core-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/core-service
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${core.blocking.kafka-properties.bootstrap-servers}

core:
  enabled: true
  blocking:
    enabled: true
    kafka-properties:
      blocking-topic:
        name: "user_blocked"
      bootstrap-servers: localhost:29092
  credit:
    mq:
      enabled: true
      credit-create-request:
        name: "credit.create.request"
      credit-create-response:
        name: "credit.create.response"
      exchange: "credit-exchange"
      queues:
        creditCreateRequest: ${core.credit.mq.credit-create-request.name}
        creditCreateResponse: ${core.credit.mq.credit-create-response.name}
        paymentRequest: "credit.payment.request"
        paymentResponse: "credit.payment.response"
      routing-keys:
        creditCreateRequest: "credit.create.request"
        creditCreateResponse: "credit.create.response"
        paymentRequest: "credit.payment.request"
        paymentResponse: "credit.payment.response"
