spring:
  application:
    name: core-query
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/core-service-query
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
    url: jdbc:postgresql://postgres:5432//core-service-query
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://46.29.239.208:8089/realms/app-realm
          jwk-set-uri: http://46.29.239.208:8089/realms/app-realm/protocol/openid-connect/certs

query:
  websocket:
    transaction:
      enabled: true
      client:
        path: "/ws/client/transaction"
      employee:
        path: "/ws/employee/transaction"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
