spring:
  liquibase:
    url: jdbc:postgresql://localhost:5434/core-service-query
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/core-service-query
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: 46.29.239.208:29094
query:
  kafka:
    listener:
      enabled: true
    account-topic:
      name: "ACCOUNT"
    transaction-topic:
      name: "TRANSACTION"

server:
  port: 8081