spring:
  liquibase:
    url: jdbc:postgresql://46.29.239.208:5434/postgres
  r2dbc:
    url: r2dbc:postgresql://46.29.239.208:5434/postgres
    username: core_query_user
    password: core_query_password_strongvery
  kafka:
    bootstrap-servers: 46.29.239.208:29094
query:
  kafka:
    listener:
      enabled: true
    account-topic:
      name: "ACCOUNT"
    transaction-topic:
      name: "TRANSACTION"

server:
  port: 8083